/**
 * Records what V8's `Date.parse` makes of every distinct `lstart` string in the
 * fixtures, so the Rust port can be checked against it exactly rather than for
 * plausibility.
 *
 * `Date.parse` is implementation-defined for these formats and V8's is lenient
 * — it accepts the C, en_GB and de_DE forms and rejects only zh_CN. That is not
 * something to reimplement from the specification, because the specification
 * does not describe it. Record it instead.
 *
 * TZ is pinned so the file is reproducible on any machine; the Rust test
 * converts against the same zone explicitly.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const TZ = 'UTC';
if (process.env['TZ'] !== TZ) {
  throw new Error(`run with TZ=${TZ} (npm run gen:lstart-corpus)`);
}

const dir = fileURLToPath(new URL('../test/fixtures/', import.meta.url));
/* The same field the parser sees: everything between the PID and the user
   column, which is what the ps-static patterns capture. */
const YEAR_DIGITS = 4;
const RE = new RegExp(
  String.raw`^\s*\d+\s+(\S.*?\d{1,2}:\d{2}:\d{2}(?:\s+\d{${YEAR_DIGITS}})?)\s+\S+\s+\S+\s+`,
);

const seen = new Map<string, number | null>();
for (const name of readdirSync(dir).filter((f) => f.startsWith('ps-static'))) {
  for (const line of readFileSync(`${dir}${name}`, 'utf8').split('\n').slice(1)) {
    const m = RE.exec(line);
    if (!m) continue;
    const field = m[1]!;
    if (seen.has(field)) continue;
    const t = Date.parse(field.trim().replace(/\s+/g, ' '));
    seen.set(field, Number.isFinite(t) ? t : null);
  }
}

const out = {
  note: 'What V8 Date.parse returns for every distinct lstart field in the fixtures. Generated by scripts/gen-lstart-corpus.ts.',
  tz: TZ,
  cases: [...seen].map(([field, epochMs]) => ({ field, epochMs })),
};
const path = fileURLToPath(
  new URL('../crates/sysmon-core/tests/fixtures/lstart-corpus.json', import.meta.url),
);
writeFileSync(path, `${JSON.stringify(out, null, 1)}\n`);
process.stdout.write(`wrote ${out.cases.length} lstart cases (${out.cases.filter((c) => c.epochMs === null).length} unparseable)\n`);
